spring:
  application:
    name: dental-clinic-backend
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/dentalclinic
    username: postgres
    password: '12345'
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding=true:

token:
  expiration-time: 600000
  signing:
    key: '53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855'