spring:
  application:
    name: dental-clinic-backend
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding=true:

token:
  expiration-time: ${JWT_EXP_TIME:600000}
  signing:
    key: ${JWT_SECRET_KEY:53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855}